/* AUTO-GENERATED by build.js from README.md. Do not edit by hand.
   Edit the shelf in README.md, then run: node build.js */

window.CATEGORIES = [
  {
    "id": "design-interface",
    "name": "Design & Interface",
    "blurb": "Skills that raise the floor on anything visual - UI, brand, generative art.",
    "glyph": "◑"
  },
  {
    "id": "copywriting",
    "name": "Copywriting",
    "blurb": "Words that carry their weight. Voice, tone, and the craft of the sentence.",
    "glyph": "¶"
  },
  {
    "id": "marketing-growth",
    "name": "Marketing & Growth",
    "blurb": "CRO, SEO, email, positioning - the unglamorous engine room of growth.",
    "glyph": "↗"
  },
  {
    "id": "docs-decks",
    "name": "Docs & Decks",
    "blurb": "Real .docx, .pptx, .xlsx and .pdf - not Markdown wearing a costume.",
    "glyph": "▤"
  },
  {
    "id": "image-motion",
    "name": "Image & Motion",
    "blurb": "Prompts, frames and loops. The skills for making things move and shine.",
    "glyph": "✶"
  },
  {
    "id": "build-tooling",
    "name": "Build & Tooling",
    "blurb": "Meta-skills, MCP servers and the plumbing that makes the rest sing.",
    "glyph": "⌗"
  }
];

window.TIERS = {
  "essential": {
    "id": "essential",
    "label": "Essential",
    "note": "Install before anything else.",
    "rank": 3
  },
  "recommended": {
    "id": "recommended",
    "label": "Recommended",
    "note": "Earns its place in the rotation.",
    "rank": 2
  },
  "worth": {
    "id": "worth",
    "label": "Worth a look",
    "note": "Niche, but excellent at its one thing.",
    "rank": 1
  }
};

window.KINDS = {
  "skill": {
    "id": "skill",
    "label": "Skill",
    "plural": "Skills",
    "glyph": "▣",
    "blurb": "A folder of instructions Claude loads to do a task your way.",
    "sourceVerb": "View source",
    "specLabel": "Effort"
  },
  "mcp": {
    "id": "mcp",
    "label": "MCP",
    "plural": "MCPs",
    "glyph": "◆",
    "blurb": "A server that wires Claude into a live tool or data source.",
    "sourceVerb": "View server",
    "specLabel": "Setup"
  }
};

window.FLAGSHIP = {
  "id": "phils-skill",
  "flagship": true,
  "kind": "skill",
  "name": "Phil's Skill",
  "cat": "build",
  "tier": "essential",
  "pick": true,
  "author": "Phil Maggs",
  "repo": "philmaggs/phils-skills",
  "url": "https://github.com/philmaggs/phils-skills",
  "tested": "2026-06",
  "effort": "One command",
  "headline": "Find the right skill in one line.",
  "oneLiner": "Describe what you need in plain words and it does the rest — search, match, install.",
  "verdict": "Every other entry on this shelf is something I found. This is the one I built. It's the index made executable. Tell it what you're doing in plain language, say 'find me something for turning a CSV into a deck', and it reads the live shelf, hands back the two or three that actually fit with my verdict, and gives you the line to install the winner. No hunting across repos. No wondering whether a thing is any good. The taste is already baked in, because only skills that earned a place on the shelf are searchable. It's the front door to everything else here.",
  "useWhen": "You know the job, not the skill. Describe the problem and let it pull the right tool off the shelf.",
  "tags": [
    "meta",
    "search",
    "installer",
    "the house skill"
  ],
  "install": {
    "npx": {
      "label": "Terminal",
      "lines": [
        "npx skills add philmaggs/phils-skills --skill phils-skill"
      ],
      "note": "Then just describe the job. That's the whole trick."
    }
  }
};

window.SKILLS = [
  {
    "id": "figma-mcp",
    "kind": "mcp",
    "name": "Figma MCP",
    "cat": "design-interface",
    "tier": "essential",
    "pick": true,
    "author": "Figma",
    "repo": "figma/dev-mode-mcp-server",
    "url": "https://github.com/figma/dev-mode-mcp-server",
    "tested": "2026-05",
    "oneLiner": "Hands Claude your actual Figma frames - real layers, variables and specs, not a screenshot.",
    "verdict": "This is the one that closes the gap between the design file and the build. Point Claude at a frame and it reads the real structure - the auto-layout, the variables, the spacing you actually set - instead of squinting at a flat picture and guessing. The output respects your tokens because it can finally see them. Setup takes a minute and Dev Mode is a prerequisite, but once it's running, “make it match the Figma” stops being a negotiation. If you ship design-to-code, this isn't optional.",
    "useWhen": "Turning a real Figma design into faithful code without redrawing it by eye.",
    "tags": [
      "figma",
      "design-to-code",
      "dev mode",
      "official"
    ],
    "connects": "Figma files & Dev Mode"
  },
  {
    "id": "frontend-design",
    "kind": "skill",
    "name": "Frontend Design",
    "cat": "design-interface",
    "tier": "essential",
    "pick": true,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "Embeds a real design system so generated UI stops looking like generated UI.",
    "verdict": "The one that quietly fixed the thing everyone moans about. It bans the tells - the purple gradients, Inter everywhere, the same rounded corners on everything - and swaps default taste for an actual point of view. Same prompt, output that looks like a grown-up made it. It won't replace a designer on client work, but your internal tools stop needing an apology. If you adopt one skill off this whole list, make it this one.",
    "useWhen": "Any time Claude is touching an interface and you don't fancy spending the afternoon de-slopping it.",
    "tags": [
      "UI",
      "design system",
      "anti-slop",
      "official"
    ]
  },
  {
    "id": "hallmark",
    "kind": "skill",
    "name": "Hallmark",
    "cat": "design-interface",
    "tier": "essential",
    "pick": false,
    "author": "Nutlope",
    "repo": "nutlope/hallmark",
    "url": "https://github.com/nutlope/hallmark",
    "tested": "2026-06",
    "oneLiner": "Audits a live site for AI-slop and redesigns it - greenfield pages, redesigns, or design pulled from a URL or screenshot.",
    "verdict": "I pointed it at my own site half-expecting cosmetic notes and got a proper audit - not a list of gripes, but the real tells: weak hierarchy, lazy spacing, the defaults that quietly scream “generated”. Then it fixed them. The site is measurably better for it and I didn't have to fight it to get there. Most “design” skills flatter your input; this one improves it. If your pages work but look a touch AI-made, this is the fastest way out.",
    "useWhen": "A page works but looks generic and you want a real audit-and-redesign, not a fresh coat of paint.",
    "tags": [
      "design",
      "audit",
      "anti-slop",
      "redesign"
    ]
  },
  {
    "id": "artifacts-builder",
    "kind": "skill",
    "name": "Artifacts Builder",
    "cat": "design-interface",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-04",
    "oneLiner": "Multi-component interactive artifacts on React 18 + TypeScript + Tailwind + shadcn/ui.",
    "verdict": "Where Frontend Design sets the taste, this one sets the scaffolding. Hand it a fuzzy idea and you get back something with structure - real components, sensible state, a stack you'd actually ship - not a clever toy. It rewards a sharp brief and punishes a vague one, so write the brief. Run it next to Frontend Design and the job splits cleanly: one decides how it looks, the other how it's built.",
    "useWhen": "Prototyping something that needs to behave, not just sit there looking pretty.",
    "tags": [
      "React",
      "Tailwind",
      "shadcn",
      "prototype"
    ]
  },
  {
    "id": "brand-guidelines",
    "kind": "skill",
    "name": "Brand Guidelines",
    "cat": "design-interface",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "Applies a brand identity - colours, type, the rules - so output stops drifting off-brand.",
    "verdict": "Deceptively boring, genuinely useful. Feed it the palette, the typefaces, the do's and don'ts, and everything downstream stops being a fight. The clever part isn't that it knows your brand - it's that it doesn't forget it by slide nine. The closest thing to handing Claude the brand book and trusting it read past the cover.",
    "useWhen": "You have a brand to protect and a team that keeps nudging things off it.",
    "tags": [
      "brand",
      "consistency",
      "identity",
      "official"
    ]
  },
  {
    "id": "canvas-generative-art",
    "kind": "skill",
    "name": "Canvas / Generative Art",
    "cat": "design-interface",
    "tier": "worth",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-03",
    "oneLiner": "Museum-quality generative art in p5.js with seeded randomness and live parameters.",
    "verdict": "The show-off of the collection, and it's earned the right. Seeded randomness lets you wander a whole space of variations and then walk straight back to the exact one you loved. It's 90% visual and 10% text by design, and - unlike most generative toys - it knows the line between sophisticated and cartoonish. Not an everyday tool, but when you need a cover or a backdrop with actual intent, nothing else here is close.",
    "useWhen": "You want art with intent - a cover, a backdrop, a print - not clip-art filler.",
    "tags": [
      "p5.js",
      "generative",
      "print",
      "creative coding"
    ]
  },
  {
    "id": "tone-of-voice",
    "kind": "skill",
    "name": "Tone of Voice",
    "cat": "copywriting",
    "tier": "essential",
    "pick": true,
    "author": "Community",
    "repo": "agentskills.io",
    "url": "https://agentskills.io",
    "tested": "2026-05",
    "oneLiner": "Teaches Claude your voice from a handful of samples, then holds it across everything.",
    "verdict": "The single highest-leverage thing you can teach an assistant, and this does it without ceremony. Drop in a few pieces you're proud of, name the tics you love and the ones you don't, and the drift just stops. Generic AI copy is the default state of the universe and this is the cheapest way out of it. It won't make you a better writer, but it stops Claude quietly undoing the work of being one. Everyone's first real skill should be a voice skill.",
    "useWhen": "Always - the moment more than one thing goes out written “as you”, you want this holding the line.",
    "tags": [
      "voice",
      "tone",
      "editing",
      "consistency"
    ]
  },
  {
    "id": "longform-editor",
    "kind": "skill",
    "name": "Longform Editor",
    "cat": "copywriting",
    "tier": "recommended",
    "pick": false,
    "author": "Community",
    "repo": "agentskills.io",
    "url": "https://agentskills.io",
    "tested": "2026-04",
    "oneLiner": "A ruthless line editor - cuts, tightens, and asks what the piece is really about.",
    "verdict": "Most editing skills flatter you. This one is rude in the useful way - it cuts, it questions, and it kills the darling sentence you were proud of and were wrong to keep. The tell is the quality gate: after a couple of clean passes it starts asking what can come out rather than what can go in. That instinct alone earns its keep.",
    "useWhen": "The draft is done and you need a second set of eyes that won't be polite about it.",
    "tags": [
      "editing",
      "longform",
      "structure",
      "craft"
    ]
  },
  {
    "id": "naming-taglines",
    "kind": "skill",
    "name": "Naming & Taglines",
    "cat": "copywriting",
    "tier": "worth",
    "pick": false,
    "author": "Community",
    "repo": "agentskills.io",
    "url": "https://agentskills.io",
    "tested": "2026-02",
    "oneLiner": "Generates names and lines with rationale, not just a list of words to ignore.",
    "verdict": "Naming is mostly heartbreak and this won't fix that - but it beats the blank page handily. The trick is that it shows its working: why a name lands, what it evokes, where it'll trip. You'll bin most of them, as you should. Low keeper rate, good keepers - which is honestly the entire job.",
    "useWhen": "Early, when you need fifty bad names to find the one that isn't.",
    "tags": [
      "naming",
      "taglines",
      "brainstorm",
      "brand"
    ]
  },
  {
    "id": "marketing-skills",
    "kind": "skill",
    "name": "Marketing Skills",
    "cat": "marketing-growth",
    "tier": "essential",
    "pick": true,
    "author": "Corey Haines",
    "repo": "coreyhaines31/marketingskills",
    "url": "https://github.com/coreyhaines31/marketingskills",
    "tested": "2026-05",
    "oneLiner": "Twenty-plus skills - CRO, copy, SEO, email, A/B tests, growth - in a single install.",
    "verdict": "Built for the founder wearing every hat at once, and it shows - in the good way. Instead of hunting individual skills across a dozen repos, here's one collection covering the whole growth surface in a consistent voice. Not every skill inside is a ten, but the median is high and the breadth is the point. If marketing is the side-quest you keep losing, start here.",
    "useWhen": "You're a small team doing marketing between everything else and need a baseline that doesn't embarrass you.",
    "tags": [
      "CRO",
      "SEO",
      "email",
      "growth",
      "collection"
    ]
  },
  {
    "id": "seo-content-brief",
    "kind": "skill",
    "name": "SEO Content Brief",
    "cat": "marketing-growth",
    "tier": "recommended",
    "pick": false,
    "author": "Community",
    "repo": "agentskills.io",
    "url": "https://agentskills.io",
    "tested": "2026-04",
    "oneLiner": "Turns a target keyword into a structured, intent-mapped brief a writer can actually use.",
    "verdict": "Most SEO output reads like it was written for a crawler and nobody else. This one starts from intent - what the reader is actually trying to do - and builds the outline outward from there. The briefs are tight, the headings earn their place, and it resists the urge to pad for word count. A quietly excellent first draft of the thinking, which is the bit most people skip.",
    "useWhen": "Before you write the article, when you want the shape of it to be right.",
    "tags": [
      "SEO",
      "content",
      "briefs",
      "intent"
    ]
  },
  {
    "id": "slack-mcp",
    "kind": "mcp",
    "name": "Slack MCP",
    "cat": "marketing-growth",
    "tier": "recommended",
    "pick": false,
    "author": "Community",
    "repo": "modelcontextprotocol/servers",
    "url": "https://github.com/modelcontextprotocol/servers",
    "tested": "2026-04",
    "oneLiner": "Reads channels and posts on your behalf - campaign updates and standups without the tab-switch.",
    "verdict": "Less glamorous than it sounds, more useful than you'd expect. Claude can read a noisy launch channel, draft the update, and post it where the team already lives. Get the permission scoping right - read where you mean read - and Slack stops being a context sink and starts being where work lands. Connective tissue rather than a headline act, and none the worse for it.",
    "useWhen": "You want Claude to digest or post into Slack instead of you relaying it by hand.",
    "tags": [
      "slack",
      "comms",
      "updates",
      "automation"
    ],
    "connects": "Slack channels, threads & DMs"
  },
  {
    "id": "market-research-scraper",
    "kind": "skill",
    "name": "Market Research Scraper",
    "cat": "marketing-growth",
    "tier": "worth",
    "pick": false,
    "author": "BrowserAct",
    "repo": "browseract/skills",
    "url": "https://github.com/browseract/skills",
    "tested": "2026-03",
    "oneLiner": "Pulls pricing, ratings and positioning from a marketplace listing without tripping the bots.",
    "verdict": "A one-trick specialist, and the trick is a good one. Point it at a product or a search and it comes back with the competitive picture - price, reviews, where a thing actually sits - in a single pass, while the browser-automation layer quietly does the boring job of not getting blocked. It trades an afternoon of forty open tabs for one prompt. That's a trade I'll make every time.",
    "useWhen": "Sizing up a market or a competitor and you'd rather not open forty tabs by hand.",
    "tags": [
      "research",
      "scraping",
      "competitive",
      "ecommerce"
    ]
  },
  {
    "id": "pptx-builder",
    "kind": "skill",
    "name": "PPTX Builder",
    "cat": "docs-decks",
    "tier": "essential",
    "pick": true,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "Generates genuine PowerPoint - editable shapes and text, not a screenshot of a deck.",
    "verdict": "The skill that ended my relationship with “export this Markdown to slides” hacks. It makes real .pptx - proper text boxes, real shapes, a layout you can open in PowerPoint without weeping. Visual QA is baked in, on the sane assumption that something is always slightly off. Pair it with the spreadsheet skill and a CSV becomes a board-ready deck in one move.",
    "useWhen": "Anyone downstream is going to open the file in PowerPoint and judge you by it.",
    "tags": [
      "pptx",
      "slides",
      "office",
      "official"
    ]
  },
  {
    "id": "notion-mcp",
    "kind": "mcp",
    "name": "Notion MCP",
    "cat": "docs-decks",
    "tier": "recommended",
    "pick": false,
    "author": "Notion",
    "repo": "makenotion/notion-mcp-server",
    "url": "https://github.com/makenotion/notion-mcp-server",
    "tested": "2026-05",
    "oneLiner": "Lets Claude read and write your Notion - docs, databases, the lot - as a first-class citizen.",
    "verdict": "The quiet workhorse if you live in Notion. Claude pulls the brief from a database, drafts the doc, and files it back where the team expects to find it - no copy-paste relay race. It respects your structure instead of dumping a wall of text onto a fresh page. The official server is refreshingly painless to set up. If your team's brain is in Notion, this hands Claude a key to the building.",
    "useWhen": "Your source of truth lives in Notion and you want Claude working inside it, not beside it.",
    "tags": [
      "notion",
      "docs",
      "knowledge base",
      "official"
    ],
    "connects": "Notion workspaces & databases"
  },
  {
    "id": "pdf-toolkit",
    "kind": "skill",
    "name": "PDF Toolkit",
    "cat": "docs-decks",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-04",
    "oneLiner": "Extraction, form-filling and batch redaction - the canonical progressive-disclosure skill.",
    "verdict": "Sounds like a press release - “AI does PDFs” - right up until it quietly changes how you handle contracts. A pre-written script reads the form fields without dragging the whole document into context, so it's fast and deterministic where it counts. It's the textbook example of a skill done properly, and it earns the cliché. The least glamorous tool here, and the one you'll reach for most.",
    "useWhen": "Anything PDF - pulling data out, filling forms in, redacting at volume.",
    "tags": [
      "pdf",
      "extraction",
      "forms",
      "official"
    ]
  },
  {
    "id": "xlsx-builder",
    "kind": "skill",
    "name": "XLSX Builder",
    "cat": "docs-decks",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "Real spreadsheets with live formulas - dynamic, not hard-coded numbers.",
    "verdict": "The difference between this and “export the numbers to a table” is one word: formulas. It writes live ones, so the model stays alive - change an input and the sheet recalculates the way a spreadsheet is meant to, instead of sitting there as a fossil of numbers that were true once. Zero-error validation is the house rule, which is the only standard worth having when people are going to trust the totals. It doesn't show off - it just doesn't lie to you.",
    "useWhen": "The deliverable is a model someone will poke at, not a static table.",
    "tags": [
      "xlsx",
      "spreadsheets",
      "formulas",
      "office"
    ]
  },
  {
    "id": "docx-builder",
    "kind": "skill",
    "name": "DOCX Builder",
    "cat": "docs-decks",
    "tier": "worth",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-03",
    "oneLiner": "Proper Word docs - tracked changes, TOC, footnotes, multi-column, the lot.",
    "verdict": "The most thankless member of the Office trio, and the one legal teams quietly adore. Tracked changes, tables in real units, headers and footers that actually behave - it handles the fiddly Word machinery that usually detonates on export. You'll only notice it the day it saves you from reformatting a forty-page document by hand, which is precisely the day you'll be grateful.",
    "useWhen": "The output has to survive a Word-native review process with its formatting intact.",
    "tags": [
      "docx",
      "word",
      "documents",
      "office"
    ]
  },
  {
    "id": "google-drive-mcp",
    "kind": "mcp",
    "name": "Google Drive MCP",
    "cat": "docs-decks",
    "tier": "worth",
    "pick": false,
    "author": "Community",
    "repo": "modelcontextprotocol/servers",
    "url": "https://github.com/modelcontextprotocol/servers",
    "tested": "2026-03",
    "oneLiner": "Search, read and reference your Drive so Claude works from the real document, not your paraphrase.",
    "verdict": "The cure for the telephone game. Instead of paraphrasing the brief into the chat and hoping, you let Claude open the actual file in Drive and work from the source - fewer garbled facts, citations you can stand behind. OAuth is the one speed bump, and it's a one-time one. Unflashy - but once your assistant reads the real document instead of your summary of it, going back feels like working blindfolded.",
    "useWhen": "The material Claude needs is sitting in Drive and you'd rather it read the source.",
    "tags": [
      "google drive",
      "docs",
      "search",
      "grounding"
    ],
    "connects": "Drive files, Docs & Sheets"
  },
  {
    "id": "image-prompt-generator",
    "kind": "skill",
    "name": "Image Prompt Generator",
    "cat": "image-motion",
    "tier": "essential",
    "pick": true,
    "author": "huangserva",
    "repo": "huangserva/skill-prompt-generator",
    "url": "https://github.com/huangserva/skill-prompt-generator",
    "tested": "2026-05",
    "oneLiner": "Turns a described visual into professional, optimised prompts for image models.",
    "verdict": "Prompt engineering for images is its own discipline, and most of us are amateurs at it. This one takes the picture in your head and writes the prompt language that actually gets you there - composition, lighting, lens, the vocabulary the models respond to. It collapses an hour of trial-and-error into one good first attempt. The closest thing to a translator between taste and tool.",
    "useWhen": "You can picture the image but keep fighting the model to get it out.",
    "tags": [
      "prompts",
      "text-to-image",
      "generative",
      "visual"
    ]
  },
  {
    "id": "slack-gif-creator",
    "kind": "skill",
    "name": "Slack GIF Creator",
    "cat": "image-motion",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-04",
    "oneLiner": "Animated GIFs tuned for Slack - eight motion concepts, ten ready-made themes.",
    "verdict": "Pure delight, and it knows exactly how small it is. Shake, pulse, bounce, spin, fade - eight motion concepts and a stack of themes mean your team's in-jokes finally get a production budget. It will not change your business. It will absolutely improve a Thursday. Sometimes that's the whole brief, and this one nails it.",
    "useWhen": "Morale, celebration, or a launch that deserves more than a thumbs-up emoji.",
    "tags": [
      "gif",
      "animation",
      "slack",
      "fun"
    ]
  },
  {
    "id": "personal-voice-builder",
    "kind": "skill",
    "name": "Personal Voice Builder",
    "cat": "build-tooling",
    "tier": "essential",
    "pick": true,
    "author": "Phillip Maggs",
    "repo": "philmaggs/phils-skills",
    "url": "https://github.com/philmaggs/phils-skills/tree/main/skills/personal-voice-builder",
    "tested": "2026-06",
    "oneLiner": "Turns your own messages into a reusable skill that makes Claude write as you, not as a generic professional.",
    "verdict": "The one on this shelf I built rather than found. I made a one-off voice skill from my Slack history, it worked too well to keep to myself, so I generalised it to run off any source. Point it at wherever you actually write - Slack, email, Notion - and it collects a big verbatim sample, works out how your tone shifts by audience, and writes you an installable style skill plus an evidence-backed analysis of how you communicate. Every claim it makes is pinned to a real quote of yours, it refuses to run on a thin sample, and it scores its own output against your real messages before handing over. It captures the contrast between your one-word replies and your long memos, which is where a voice actually lives.",
    "useWhen": "You want Claude to sound like you across chat, email and docs, instead of falling back on a polite generic voice.",
    "tags": [
      "voice",
      "writing style",
      "meta",
      "personal"
    ]
  },
  {
    "id": "skill-creator",
    "kind": "skill",
    "name": "Skill Creator",
    "cat": "build-tooling",
    "tier": "essential",
    "pick": true,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "The meta-skill: a skill for writing skills, with the frontmatter contract enforced.",
    "verdict": "The bootstrap. It scaffolds new skills, enforces the YAML contract, and - most usefully - helps you write the description field, the bit nearly everyone fluffs and the bit that decides whether a skill ever fires. Pair it with the MCP builder and you've got a toolkit that extends itself. If you plan to live in this ecosystem rather than visit, this is the second thing you install.",
    "useWhen": "The moment you stop borrowing skills and start writing your own.",
    "tags": [
      "meta",
      "authoring",
      "scaffolding",
      "official"
    ]
  },
  {
    "id": "github-mcp",
    "kind": "mcp",
    "name": "GitHub MCP",
    "cat": "build-tooling",
    "tier": "essential",
    "pick": false,
    "author": "GitHub",
    "repo": "github/github-mcp-server",
    "url": "https://github.com/github/github-mcp-server",
    "tested": "2026-05",
    "oneLiner": "Gives Claude the keys to your repos - issues, pull requests, reviews, the whole workflow.",
    "verdict": "The official server, and the breadth shows. Claude can triage an issue, open a PR, leave a review, and check a failing Action without you leaving the conversation. The coverage is comprehensive rather than cute, and the error messages tell you what actually went wrong. Pair it with a code-review skill and you've got a real pair of hands on the repo. If your work has a GitHub side, install this early.",
    "useWhen": "You want Claude operating on real repos - not pasting diffs back and forth.",
    "tags": [
      "github",
      "git",
      "pull requests",
      "official"
    ],
    "connects": "Repos, issues, PRs & Actions"
  },
  {
    "id": "mcp-builder",
    "kind": "skill",
    "name": "MCP Builder",
    "cat": "build-tooling",
    "tier": "recommended",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-05",
    "oneLiner": "Generates Model Context Protocol servers from a plain description of what you need.",
    "verdict": "Where Skills teach the workflow, MCPs expose the tools - and this writes the server that joins the two. It favours comprehensive API coverage over cute one-off helpers, names things sensibly, and writes error messages a human can act on. The ten-question intake feels like overkill until you see how much it sharpens the result. Plumbing - but the good kind you stop thinking about the moment it's in.",
    "useWhen": "You need Claude to reach a real external system and want the bridge built properly.",
    "tags": [
      "MCP",
      "servers",
      "integration",
      "official"
    ]
  },
  {
    "id": "linear-mcp",
    "kind": "mcp",
    "name": "Linear MCP",
    "cat": "build-tooling",
    "tier": "worth",
    "pick": false,
    "author": "Linear",
    "repo": "linear/linear-mcp",
    "url": "https://github.com/linear/linear-mcp",
    "tested": "2026-03",
    "oneLiner": "Turns a loose intention into a properly-shaped Linear issue, assigned and in the right cycle.",
    "verdict": "A focused little server that does one workflow cleanly: it turns “we should fix the onboarding drop-off” into a real issue with the right project, labels and cycle. It won't run your sprint, but it kills the friction that means good ideas never get logged. Niche, tidy, exactly as ambitious as it needs to be - the kind of MCP you forget is even an integration.",
    "useWhen": "Capturing work into Linear without breaking flow to fill in the form.",
    "tags": [
      "linear",
      "issues",
      "planning",
      "ops"
    ],
    "connects": "Linear issues, projects & cycles"
  },
  {
    "id": "webapp-testing",
    "kind": "skill",
    "name": "Webapp Testing",
    "cat": "build-tooling",
    "tier": "worth",
    "pick": false,
    "author": "Anthropic",
    "repo": "anthropics/skills",
    "url": "https://github.com/anthropics/skills",
    "tested": "2026-03",
    "oneLiner": "Drives a real browser with Playwright - reconnaissance first, then action.",
    "verdict": "The discipline is the whole point: look before you leap - wait for the page to settle, screenshot it, find the selectors, then act. Never blind. That's why it doesn't flail the way naive automation does the moment a page loads half a second late. It won't decide what your tests should prove - that's still on you - but as a steady pair of hands on a live app, it's hard to fault. The unglamorous kind of reliable you stop worrying about.",
    "useWhen": "You need to verify a running web app actually does what it claims.",
    "tags": [
      "testing",
      "playwright",
      "browser",
      "QA"
    ]
  }
];
